#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# Remove msh file
rm cylinderStruct3D.msh
#------------------------------------------------------------------------------
