#!/bin/sh
set -e
cd ${0%/*} || exit 1    # Run from this directory

# Generate mesh
gmsh cylinderStruct.geo -3 -format msh2

# Convert mesh
gmshToFoam cylinderStruct.msh

# Change patch to empty
sed -i "22s/patch/empty/" constant/polyMesh/boundary

# Decompose domain
decomposePar

# Run application
echo "Launching buoyantPimpleFoam application..."
mpirun -n 8 buoyantPimpleFoam -parallel > log.buoyantPimpleFoam
echo "All done"
